### ISSUE TITLE
Validation for Item Quantity in PO Demo is Incorrect

### ISSUE THREAD

**Issue by zian3** [corda/cordapp-template#1]
Hello, I've found an issue with checking the total quantity of items when submitting a PO in the demo application - the sum checks for less than or equal to 10 rather than 100.

Line 92 of src/main/kotlin/com.example/contract/PurchaseOrderContract.kt is:

`"You can only order up to 100 items in total." by (out.po.items.map(Item::amount).sum() <= 10)`

Should be:

`"You can only order up to 100 items in total." by (out.po.items.map(Item::amount).sum() <= 100)`

**Comment by joeldudleyr3** [comment]
Thanks Zian - good spot! Feel free to submit a pull request with a fix.

**Comment by roger3cev** [comment]
Cheers - amended!
