### ISSUE TITLE
Illegal option -o pipefail

### ISSUE THREAD

**Issue by aswinkumarrhex** [corda/cordapp-template#63]
Hi, I am trying to set up the CORDA on ubuntu 12.04(virtual Machine).
the build is successful for M8 version and when i try to run the nodes from 
/kotlin/build/nodes# sh runnodes i get this 
"runnodes: 4: set: Illegal option -o pipefail"
can someone help me on this issue. I have updated the bash to latest 3. It is part of the requirement i stick to 12 and not Ubuntu 14. 

Update/Edit : kotlin-source/build/nodes# ./runnodes
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm Xt error: Can't open display: %s
xterm:  DISPLAY is not set

i have installed xterm as well. still above issue persists. Kindly help 
thanks
aswink

**Comment by aswinkumarrhex** [comment]
Issue Resolved and Closed.

**Comment by mamidi1211** [comment]
How the issue got resolved? 
Can you share the solution?
