### ISSUE TITLE
Directory Tree Missing 

### ISSUE THREAD

**Issue by aswinkumarrhex** [corda/cordapp-template#69]
hI THIS IS MY 2ND POST HERE!!
kindly help ... I have updated my Ubuntu to 16 and was able to successfully build the corda(Master9) then successfully built  ./gradlew deploynodes post which i should be able to run my Nodes using ./runnodes

sadly cd kotlin-source/build/nodes this tree inside ......am i missing something ?
please Help i am running behind schedule on this !

regards

**Comment by joeldudleyr3** [comment]
Hi - sorry for the delay!

After building the nodes, you have to run `cd kotlin-source/build/nodes` then `sh runnodes` - does that work?

**Comment by aswinkumarrhex** [comment]
Hey Joel thank you so much !
Like I said earlier the build is successful but the mentioned directory tree 
Lotion-source/build/nodes ain't available there 
Instead all I see is 
Kotlin -source/
/src
*build.gradle
Not sure how to proceed here !!

**Comment by joeldudleyr3** [comment]
So one thing I see is that you haven't capitalised the 'N' in 'deployNodes' in your message above. Do you get a "build successful" msg after building the nodes?

Also, is the "java-source/build/nodes" directory present after running deployNodes?

**Comment by aswinkumarrhex** [comment]
hey Joel,
```
/opt/Workspace/corda$
BUILD SUCCESSFUL
Total time: 20.894 `secs`
then i moved over to 
`/opt/Workspace/cordapp-template$`
execuited a 
```
./gradlew deployNodes
BUILD FAILED
Total time: 43.179 secs
* What went wrong:
A problem occurred evaluating project ':java-source'.
> Could not resolve all dependencies for configuration ':java-source:runtime'.
   > Could not find net.corda:core:0.11-SNAPSHOT.
     Searched in the following locations:
         file:xxxxxx/.m2/repository/net/corda/core/0.11-SNAPSHOT/maven-metadata.xml
```
my guess if cordapp-template should be inside corda for it to find the snapshot 0.11 ???
i remember checking out the latest M9 from git

**Comment by aswinkumarrhex** [comment]
Joel,
I had my lady luck smirk rather than smile at me! 
i moved the cordapp-template$ into the corda folder( did not know this before !!!!) then moved over to 
`./runnodes`
i got this 
```
/Workspace/corda/cordapp-template/kotlin-source/build/nodes$ grep -i x11 /etc/ssh/sshd_config
X11Forwarding yes
X11DisplayOffset 10
```
installed my x11 still getting the above...not sure how to proceed 
environment : I access the Ubuntu 16 hosted on a VM using putty.. even tried 
SSH--X11 Forwarding

> X displaylocation : localhost:0.0

no luck can you shed some light on how to resolve this ?

regards

**Comment by aswinkumarrhex** [comment]
****
i moved the cordapp-template$ into the corda folder( did not know this before !!!!) then moved over to
./runnodes
i got this
```
xterm: DISPLAY is not set
xterm: Xt error: Can't open display: %s
xterm: DISPLAY is not set
```

**Comment by joeldudleyr3** [comment]
Hi,

The error message regarding the snapshot leads me to believe you have not checked out a stable Corda milestone. You need to do this by running `git checkout release-M10`.

It looks like you also need to install xterm - you can download it here: http://invisible-island.net/xterm/#download.

**Comment by aswinkumarrhex** [comment]
joeldudleyr3 thank you again ! it works Great Job!!!
